"""Stateful resources for the media27 stack: RDS Postgres + Secrets Manager + raw-feed S3 bucket.

Removal policies are mostly DESTROY (Free Tier portfolio project — `cdk destroy`
should produce a clean teardown), except the RDS instance, which is SNAPSHOT so
the data survives any accidental stack destruction. A `pg_dump` to S3 before
destroy remains the primary backup; the snapshot is the safety net.
"""

from aws_cdk import Duration, RemovalPolicy, Stack
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_logs as logs
from aws_cdk import aws_rds as rds
from aws_cdk import aws_s3 as s3
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct


class DataStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        vpc: ec2.IVpc,
        rds_sg: ec2.ISecurityGroup,
        **kwargs: object,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # Master password is generated by Secrets Manager (never seen in code).
        # The Lambdas will receive the secret ARN as an env var and fetch the
        # password at runtime via IAM.
        self.db_secret = secretsmanager.Secret(
            self,
            "DbSecret",
            secret_name="media27/rds/credentials",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template='{"username": "media27_admin"}',
                generate_string_key="password",
                exclude_punctuation=True,
                password_length=32,
            ),
        )

        self.db = rds.DatabaseInstance(
            self,
            "Db",
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_16_6,
            ),
            # db.t3.micro is the Free Tier instance class (12 months).
            instance_type=ec2.InstanceType.of(
                ec2.InstanceClass.BURSTABLE3, ec2.InstanceSize.MICRO
            ),
            credentials=rds.Credentials.from_secret(self.db_secret),
            vpc=vpc,
            vpc_subnets=ec2.SubnetSelection(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED,
            ),
            security_groups=[rds_sg],
            allocated_storage=20,
            storage_type=rds.StorageType.GP3,
            multi_az=False,
            database_name="media27",
            backup_retention=Duration.days(1),
            delete_automated_backups=True,
            deletion_protection=False,
            publicly_accessible=False,
            cloudwatch_logs_retention=logs.RetentionDays.ONE_WEEK,
            # SNAPSHOT (not DESTROY): on `cdk destroy`, AWS takes a final
            # manual snapshot before tearing down the instance. The snapshot
            # survives independently and can restore the DB later.
            removal_policy=RemovalPolicy.SNAPSHOT,
        )

        self.raw_bucket = s3.Bucket(
            self,
            "RawBucket",
            block_public_access=s3.BlockPublicAccess.BLOCK_ALL,
            encryption=s3.BucketEncryption.S3_MANAGED,
            enforce_ssl=True,
            versioned=False,
            lifecycle_rules=[
                s3.LifecycleRule(
                    id="glacier-30-delete-365",
                    transitions=[
                        s3.Transition(
                            storage_class=s3.StorageClass.GLACIER_INSTANT_RETRIEVAL,
                            transition_after=Duration.days(30),
                        ),
                    ],
                    expiration=Duration.days(365),
                ),
            ],
            # auto_delete_objects=True is required so `cdk destroy` can drop a
            # non-empty bucket; CDK adds a custom resource that empties it first.
            removal_policy=RemovalPolicy.DESTROY,
            auto_delete_objects=True,
        )
